### ISSUE TITLE
Contribuições

### ISSUE THREAD

**Issue by steimntz** [luiscrjunior/sei-trello#15]
Me interessei muito pelo projeto e gostaria de está ajudando, principalmente para portar para o Firefox, contudo verifiquei que você não estabeleceu nenhuma licença de código no repositório. Gostaria de saber se posso enviar pull-requests com contribuições para rodar em Firefox também.

**Comment by luiscrjunior** [comment]
Boa noite, claro, sinta-se à vontade. A portabilidade será muito bem vinda. Abraços.
