### ISSUE TITLE
Editar Cheklist do cartão no SEI

### ISSUE THREAD

**Issue by heliopartner** [luiscrjunior/sei-trello#17]
Mostrar na visualização do SEI o checklist criado no cartão Trello. Se possível, criar e editar o cheklist do cartão pelo SEI.

**Comment by heliopartner** [comment]
@luiscrjunior , existe essa possibilidade? Não sou desenvolvedor, mas tenho utilizado muito a extensão com minha Equipe no Instituto Federal de Rondônia. Essa funcionalidade ajudaria muitíssimo! Grato!

**Comment by luiscrjunior** [comment]
Boa tarde @heliopartner, ando sem muito tempo para atualizar o projeto, mas sei que essa funcionalidade é solicitada por muitos usuários. Está aqui mapeada para ser implementada. Abraços.

**Comment by luiscrjunior** [comment]
Primeira versão dessa funcionalidade disponível na versão 1.4
