### ISSUE TITLE
Número do processo na frente do cartão ao acionar "entrega"

### ISSUE THREAD

**Issue by heliopartner** [luiscrjunior/sei-trello#19]
Na tela do processo, ao acionar "Especificar data de entrega", o número do processo fica sobre o cartão, impedindo acessar o calendário.

![Untitled](https://user-images.githubusercontent.com/41652246/97097177-dbbabb80-1643-11eb-89ed-4435fb152a85.png)

**Comment by luiscrjunior** [comment]
arrumado: 4849a3980461380f6c8bf8bbdbd82d9a56bb58f0
