### ISSUE TITLE
Os cartões no SEI estão sumindo apesar do cartão no trello permanecer. Quando isso acontece tenho que criar um novo cartão e fico com dois cartões do mesmo processo no mesmo quadro.  Existe alguma maneira de combinar os quadros no trello ou de restabelecer o cartão do trello no SEI?

### ISSUE THREAD

**Issue by iarsky** [luiscrjunior/sei-trello#20]

**Comment by luiscrjunior** [comment]
Boa tarde, para mim é novidade esse comportamento. Você pode detalhar melhor esse sumiço ?

**Comment by iarsky** [comment]
Boa tarde,

Obrigado pela resposta.

Na verdade não sei o que dispara o sumiço. Como tenho mais de uma pessoa
acessando os cartões tanto no Trello como no SEI, não posso garantir que o
sumiço não tenha sido por conta de um descuido.

Em todo caso, se houve uma maneira de recuperar um cartão apagado ou de
criar um cartão no SEI redirecionandi-o a um outro cartão já criado no
Trello, isto seria uma solução.

Agradeçoi a ajuda,

Atenciosamente,

Ivan Arsky


Em qua., 28 de out. de 2020 às 16:39, Luís Júnior <notifications@github.com>
escreveu:

**Comment by iarsky** [comment]
Encontrei o problema. Estava no lugar de sempre entre a cadeira e o teclado
😅. Com a facilidade do botão do Trello no SEI, não havia percebido a
instrução de que o link do cartão está na própria descrição do cartão e
acabei apagando o número do processo no Trello. Daí o sumiço...

Bastou reescrever o número do processo no lugar correto que o cartão
reapareceu no SEI.

Agradeço a atenção.

Ivan Arsky

Em qui, 29 de out de 2020 às 16:20, Ivan Arsky <ivan.arsky@gmail.com>
escreveu:

**Comment by luiscrjunior** [comment]
Que ótimo que foi resolvido. Abraços

Em qui, 29 de out de 2020 19:01, iarsky <notifications@github.com> escreveu:
