### ISSUE TITLE
Incluir motivação e apresentação dos criadores no README

### ISSUE THREAD

**Issue by franklinbaldo** [luiscrjunior/sei-trello#31]
Primeiro, parabéns pela ideia. 

A extensão é muito boa, mas usar uma ferramenta escrita por desconhecidos pode afastar o público alvo. 

Por isso uma apresentação dos motivos e do currículo dos mantenedores seria interessante.

**Comment by luiscrjunior** [comment]
Bom dia, obrigado pelo feedback e pela ideia, está registrado.

Quanto ao código, ele está disponível nesse repositório para quem quiser visualizar e, ainda, as duas lojas fazem revisão do conteúdo para que não seja submetida nenhuma extensão com código maléfico.
