### ISSUE TITLE
Erro ao sincronizar com o Trello

### ISSUE THREAD

**Issue by gustavofbaptista1981** [luiscrjunior/sei-trello#39]
blob:file:///a9cae0f7-71bd-436e-8e00-42f70a2330ff

**Comment by gustavofbaptista1981** [comment]
![a9cae0f7-71bd-436e-8e00-42f70a2330ff](https://user-images.githubusercontent.com/83070840/125981037-832450a5-22a6-44fd-8728-f8a1326b1ccc.jpg)

**Comment by luiscrjunior** [comment]
Boa noite, por favor siga nosso [guia de instalação](https://luiscrjunior.github.io/sei-trello/instalacao.html) para sincronizar sua conta do Trello.
