### ISSUE TITLE
Erro ao adicionar cartão (na tela do SEI)

### ISSUE THREAD

**Issue by ulmateus** [luiscrjunior/sei-trello#42]
A extensão vem apresentando a alguns dias o erro de configuração:

![Erro (adicionar cartões automaticamente)](https://user-images.githubusercontent.com/90723565/133322220-7134ecff-847b-4621-b22a-84b4ca5b22e2.png)

Obs1: O funcionamento ocorria de forma normal, sem quaisquer alteração no nome do board ou da list;
Obs2: versões de browser - Firefox: Versão 92.0 (64 bits) / Google Chrome: Versão 93.0.4577.82 (Versão oficial) 64 bits

**Comment by luiscrjunior** [comment]
Extensão está funcionando normalmente. Provavelmente, trata-se de alguma configuração. Entre em contato por e-mail que posso lhe auxiliar por lá.
