### ISSUE TITLE
A aplicação não sincroniza com o TRELLO hoje

### ISSUE THREAD

**Issue by mhgodeiro** [luiscrjunior/sei-trello#44]
Apesar da chave de acesso e do Token estarem corretos, além do nome do quadro e da lista no trello também estarem corretos, hoje a extensão deixou de se vincular. Existe algum erro no servidor?

**Comment by luiscrjunior** [comment]
Extensão está funcionando normalmente. Provavelmente, trata-se de alguma configuração. Ou os servidores do Trello estavam temporariamente fora do ar. Entre em contato por e-mail que posso lhe auxiliar por lá.
