### ISSUE TITLE
CHAVE API NÃO APARECE

### ISSUE THREAD

**Issue by phggomes** [luiscrjunior/sei-trello#69]
Temos um membro novo do grupo, Ao fazer o cadastramento do novo usuário,  mesmo com acesso logado no Trello, para uso da extensão, na tela de gerar  APP-KEY, após clicar no link "http://trello.com/app-key", a próxima tela, na caixa onde deveria aparecer a CHAVE PESSOAL,   **não aparece a chave API. a caixa fica vazia .**
Alguém poderia me orientar, como corrigir esse erro?

**Comment by luiscrjunior** [comment]
Olá, eu testei hoje está OK. Certifique-se que você esteja logado no SEI antes de acessar esta URL (eu adicionei um aviso lá). Abraçis
