### ISSUE TITLE
Cartão do TRELLO não aparece na tela de "Controle de Processos" (tela inicial)

### ISSUE THREAD

**Issue by juniortrepi** [luiscrjunior/sei-trello#70]
Prezado Desenvolvedor,

Na recente atualização de versão do SEI, em que ocorreu a incorporação de novos filtros de tela de funcionalidades. os cartões do Trello deixaram de ser exibidos. 
A gente só consegue ver os cartões quando abre o processo.

Grato pela atenção que puder dispensar ao caso.

**Comment by PeritoAAlves** [comment]
Junior,
Conseguiu resolver esse problema? 
Desde a versão SEI 4.1 também estou com a mesma dificuldade.
E pra mim a principal função do SEI+Trello é a apresentação dos cartões na tela de "Controle de Processos", facilita muito o gerenciamento.

**Comment by luiscrjunior** [comment]
Olá, infelizmente a minha instituição ainda não migrou para o SEI 4.1. Sendo assim, não consigo reproduzir o erro para atualizar a extensão. Mas vou tentar um jeito.

**Comment by luiscrjunior** [comment]
Duplicate of #67

**Comment by juniortrepi** [comment]
Caro PeritoAAlves,
Ainda estou sem visualizar os cartões na tela principal.
Não deixei de usar o SEI Trello porque ele me ajuda muito com anotações e controle de prazos, além dos recursos de check-list. 
Mas realmente a aparição dos cartões na tela principal faz muuuuita falta.
