### ISSUE TITLE
Olá, infelizmente a minha instituição ainda não migrou para o SEI 4.1. Sendo assim, não consigo reproduzir o erro para atualizar a extensão. Mas vou tentar um jeito.

### ISSUE THREAD

**Issue by juniortrepi** [luiscrjunior/sei-trello#72]
Olá, infelizmente a minha instituição ainda não migrou para o SEI 4.1. Sendo assim, não consigo reproduzir o erro para atualizar a extensão. Mas vou tentar um jeito.

_Originally posted by @luiscrjunior in https://github.com/luiscrjunior/sei-trello/issues/70#issuecomment-2340932934_
            
Olá!
Obrigado pelo interesse na causa. Realmente, como disse o PeritoAAlves, o recurso dos cartões na tela principal faz muita falta.
Nunca deixei de usar o SEI Trello. E colegas que incentivei a utilizar gostaram do recurso, mas com a atualização do SEI abandonaram a extensão.

**Comment by luiscrjunior** [comment]
Obrigado, @juniortrepi . Vou investigar o que pode estar acontecendo e retorno aqui para vocês.

Duplicate of #67
